#.pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
        name: check yaml
        description: checks yaml files for parseable syntax.
        entry: check-yaml
        language: python
        types: [yaml]

    -   id: check-xml
        name: check xml
        description: checks xml files for parseable syntax.
        entry: check-xml
        language: python
        types: [xml]

    -   id: check-json
        name: check json
        description: checks json files for parseable syntax.
        entry: check-json
        language: python
        types: [json]

    -   id: end-of-file-fixer
        name: fix end of files
        description: ensures that a file is either empty, or ends with one newline.
        entry: end-of-file-fixer
        language: python
        types: [text]
        stages: [commit, push, manual]

    -   id: trailing-whitespace
        name: trim trailing whitespace
        description: trims trailing whitespace.
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
        stages: [commit, push, manual]

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
    -   id: forbid-crlf
        name: CRLF end-lines checker
        description: "Forbid files containing CRLF end-lines to be committed"
        entry: forbid_crlf
        language: python
        types: [text]
        stages: [pre-commit, pre-push, pre-merge-commit]
        minimum_pre_commit_version: "3.2.0"

    -   id: remove-crlf
        name: CRLF end-lines remover
        description: "Replace CRLF end-lines by LF ones before committing"
        entry: remove_crlf
        language: python
        types: [text]
        stages: [pre-commit, pre-push, pre-merge-commit]
        minimum_pre_commit_version: "3.2.0"

    -   id: forbid-tabs
        name: No-tabs checker
        description: "Forbid files containing tabs to be committed"
        entry: forbid_tabs
        language: python
        types: [text]
        exclude: (Makefile|debian/rules|.gitmodules)(\.in)?$
        stages: [pre-commit, pre-push, pre-merge-commit]
        minimum_pre_commit_version: "3.2.0"

    -   id: remove-tabs
        name: Tabs remover
        description: "Replace tabs by whitespaces before committing"
        entry: remove_tabs
        language: python
        args: [ --whitespaces-count, '4' ]
        types: [text]
        exclude: (Makefile|debian/rules|.gitmodules)(\.in)?$
        stages: [pre-commit, pre-push, pre-merge-commit]
        minimum_pre_commit_version: "3.2.0"
